Script started on 2017年03月12日 (週日) 21時28分35秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git don[K[K[Kconfig -l
user.email=orca2600@email.com
user.name=CarUnderwater
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github .com/<CarUnderwater>/lab1.git
bash: CarUnderwater: No such file or directory
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github..com/<CarUnderwater>/lab1.git[1P/lab1.git[1PCarUnderwater/lab1.git[C[C[C[C[C
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m exit

Script done on 2017年03月12日 (週日) 21時33分55秒
